import { Category, CategoryId } from "./types";

export const CATEGORIES: Category[] = [
  { id: "price", label: "가격/견적" },
  { id: "moq", label: "MOQ" },
  { id: "leadtime", label: "납기" },
  { id: "spec", label: "기술 사양" },
  { id: "logistics", label: "포장/물류" },
  { id: "certification", label: "인증/품질 기준" },
  { id: "payment", label: "결제 조건" },
];

export const CATEGORY_KEYWORDS: Record<CategoryId, string[]> = {
  price: [
    "가격",
    "견적",
    "단가",
    "비용",
    "price",
    "quote",
    "quotation",
    "cost",
    "fob",
    "cif",
    "달러",
    "unit price",
    "얼마",
  ],
  moq: ["moq", "최소주문", "최소 주문", "minimum order", "최소수량", "최소 수량"],
  leadtime: [
    "납기",
    "리드타임",
    "lead time",
    "delivery time",
    "delivery",
    "deliver",
    "배송 기간",
    "생산 기간",
    "일정",
    "when can you deliver",
    "how long",
    "shipping time",
    "며칠",
  ],
  spec: [
    "사양",
    "스펙",
    "규격",
    "spec",
    "specification",
    "material",
    "재질",
    "사이즈",
    "size",
    "dimension",
    "두께",
    "성능",
    "제원",
  ],
  logistics: [
    "포장",
    "물류",
    "배송",
    "운송",
    "shipping",
    "packing",
    "packaging",
    "logistics",
    "container",
    "pallet",
    "incoterm",
    "인코텀즈",
    "port",
    "항구",
  ],
  certification: [
    "인증",
    "품질",
    "quality",
    "ce",
    "iso",
    "rohs",
    "fda",
    "test report",
    "성적서",
    "certificate",
    "certification",
    "quality standard",
    "품질기준",
  ],
  payment: [
    "결제",
    "대금",
    "payment",
    "t/t",
    "tt",
    "lc",
    "신용장",
    "wire transfer",
    "deposit",
    "down payment",
    "net 30",
    "결제조건",
    "payment term",
  ],
};

export const INQUIRY_SIGNAL_KEYWORDS = [
  "문의",
  "요청",
  "부탁",
  "가능한지",
  "궁금",
  "please",
  "could you",
  "would you",
  "kindly",
  "inquiry",
  "inquire",
  "interested",
  "quotation",
  "quote",
  "order",
];
